services:
  db:
    image: mysql:8.0
    container_name: mysql-dev
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root1321
      MYSQL_DATABASE: WinderDb
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  backend:
    build: ./BackendWinder
    container_name: backend-api
    ports:
      - "5000:8080"
    environment:
      - ConnectionStrings__DefaultConnection=Server=db;Port=3306;Database=WinderDb;Uid=root;Pwd=root123;
    depends_on:
      - db

volumes:
  mysql-data: